site_name: Composable DataOps Platform
site_url: https://docs.composable.ai
site_description: Composable DataOps Platform technical documentation for big data orchestration, automation and analytics
site_author: Composable Analytics, Inc.

repo_url: https://github.com/ComposableAnalytics/Docs

theme:
    name: material
    custom_dir: 'themeExtension'
    palette:
      primary: blue grey
    logo: img/Composable_Logo.svg
    features:
      - toc.integrate


nav:
- Home: 'index.md'
- About: 'about/about.md'
#- Documentation:
- 1. Getting Started:
    - '1.1 Overview': 'Getting-Started/01.Overview.md'
    - '1.2 System Requirements': 'Getting-Started/02.System-Requirements.md'
    - '1.3 Installation and Deployment': 'Getting-Started/03.Installation-and-Deployment.md'
    - '1.4 Public Cloud Deployment': 'Getting-Started/04.Public-Cloud-Deployment.md'
- 2. Composable Platform:
    - '2.1 Overview': 'Composable-Platform/01.Overview.md'
    - '2.2 Navigation': 'Composable-Platform/02.Navigation.md'
    - '2.3 Search': 'Composable-Platform/03.Search.md'
    - '2.4 Product Areas': 'Composable-Platform/04.Product-Areas.md'
    - '2.5 System Administration': 'Composable-Platform/05.System-Administration.md'
- 3. DataFlows:
    - '3.1 Overview': 'DataFlows/01.Overview.md'
    - '3.2 Composable Designer': 'DataFlows/02.Composable-Designer.md'
    - '3.3 KeyBoard Shortcuts': 'DataFlows/03.KeyBoard-Shortcuts.md'
    - '3.4 Modules': 'DataFlows/04.Modules.md'
    - '3.5 DataFlows': 'DataFlows/05.DataFlows.md'
    - '3.6 DataFlow Reuse': 'DataFlows/06.DataFlow-Reuse.md'
    - '3.7 DataFlow Resume': 'DataFlows/DataFlow-Resume.md'
    - '3.8 DataFlow Error Handling': 'DataFlows/DataFlow-Error-Handling.md'
    - '3.9 Custom Module Extensions': 'DataFlows/07.Custom-Modules.md'
    - 3.10 Module Details:
        - 'Code Module': 'DataFlows/09.Module-Details/Code-Module.md'
        - 'DataPortal Delete Module': 'DataFlows/09.Module-Details/DataPortalDelete.md'
        - 'DataPortal Sync Module': 'DataFlows/09.Module-Details/DataPortalSync.md'
    - '3.11 Runs': 'DataFlows/10.Runs.md'
- 4. QueryViews:
    - '4.1 Overview': 'QueryViews/01.Overview.md'
    - '4.2 QueryView Basics': 'QueryViews/02.Create-QueryView.md'
    - '4.3 Paging': 'QueryViews/Paging.md'  
    - '4.4 Inputs': 'QueryViews/Inputs.md'
    - '4.5 Child QueryViews': 'QueryViews/ChildrenQueries.md'
    - '4.6 Actions': 'QueryViews/Actions.md'
    - '4.7 Hyperlinks': 'QueryViews/Hyperlinks.md'
- 5. DataPortals:
    - '5.1 Overview': 'DataPortals/01.Overview.md'
    - '5.2 DataPortal Basics': 'DataPortals/02.Create-DataPortals.md'
    - '5.3 Master Sheets': 'DataPortals/03.MasterSheet.md'
    - '5.4 Container Sheets': 'DataPortals/04.ContainerSheet.md'
    - 5.5 Control Types:
        - 'AppRun': 'DataPortals/05.Control-Details/AppRun.md'
        - 'Category': 'DataPortals/05.Control-Details/Category.md'
        - 'ClearButton': 'DataPortals/05.Control-Details/ClearButton.md'
        - 'CheckBox': 'DataPortals/05.Control-Details/CheckBox.md'
        - 'Computed': 'DataPortals/05.Control-Details/Computed.md'
        - 'Date': 'DataPortals/05.Control-Details/Date.md'
        - 'DateTime': 'DataPortals/05.Control-Details/DateTime.md'
        - 'HyperLink': 'DataPortals/05.Control-Details/HyperLink.md'
        - 'Label': 'DataPortals/05.Control-Details/Label.md'
        - 'Link': 'DataPortals/05.Control-Details/Link.md'
        - 'NumberFormatting': 'DataPortals/05.Control-Details/NumberFormatting.md'
        - 'Page': 'DataPortals/05.Control-Details/Page.md'
        - 'Phone': 'DataPortals/05.Control-Details/Phone.md'
        - 'Pill': 'DataPortals/05.Control-Details/Pill.md'
        - 'QueryView': 'DataPortals/05.Control-Details/QueryView.md'
        - 'QueryViewChooser': 'DataPortals/05.Control-Details/QueryViewChooser.md'
        - 'Radio': 'DataPortals/05.Control-Details/Radio.md'
        - 'Rating': 'DataPortals/05.Control-Details/Rating.md'
        - 'Reference': 'DataPortals/05.Control-Details/Reference.md'
        - 'SaveButton': 'DataPortals/05.Control-Details/SaveButton.md'
        - 'Spin': 'DataPortals/05.Control-Details/Spin.md'
        - 'SSN': 'DataPortals/05.Control-Details/SSN.md'
        - 'Tab': 'DataPortals/05.Control-Details/Tab.md'
        - 'Table': 'DataPortals/05.Control-Details/Table.md'
        - 'Text': 'DataPortals/05.Control-Details/Text.md'
        - 'Textarea': 'DataPortals/05.Control-Details/Textarea.md'
        - 'Voice': 'DataPortals/05.Control-Details/Voice.md'
        - 'YesNo': 'DataPortals/05.Control-Details/YesNo.md'
        - 'ZIP': 'DataPortals/05.Control-Details/ZIP.md'
    - 5.6 Container Fields:
        - 'AfterSaveUri': 'DataPortals/06.Setting-Details/AfterSaveUri.md'
        - 'CategoryCondition': 'DataPortals/06.Setting-Details/CategoryCondition.md'
        - 'ClearWhenHidden': 'DataPortals/06.Setting-Details/ClearWhenHidden.md'
        - 'Columns': 'DataPortals/06.Setting-Details/Columns.md'
        - 'ComputedCondition': 'DataPortals/06.Setting-Details/ComputedCondition.md'
        - 'ControlGroup': 'DataPortals/06.Setting-Details/ControlGroup.md'
        - 'ControlType': 'DataPortals/06.Setting-Details/ControlType.md'
        - 'CustomIndex': 'DataPortals/06.Setting-Details/CustomIndex.md'
        - 'DefaultSearchFilter': 'DataPortals/06.Setting-Details/DefaultSearchFilter.md'
        - 'DefaultValue': 'DataPortals/06.Setting-Details/DefaultValue.md'
        - 'DeleteType': 'DataPortals/06.Setting-Details/DeleteType.md'
        - 'Description': 'DataPortals/06.Setting-Details/Description.md'
        - 'DisplayName': 'DataPortals/06.Setting-Details/DisplayName.md'
        - 'EndLabel': 'DataPortals/06.Setting-Details/EndLabel.md'
        - 'FormattingLocale': 'DataPortals/06.Setting-Details/FormattingLocale.md'
        - 'FormattingOptions': 'DataPortals/06.Setting-Details/FormattingOptions.md'
        - 'Group': 'DataPortals/06.Setting-Details/Group.md'
        - 'Href': 'DataPortals/06.Setting-Details/Href.md'
        - 'InvalidMessage': 'DataPortals/06.Setting-Details/InvalidMessage.md'
        - 'MaskedCondition': 'DataPortals/06.Setting-Details/MaskedCondition.md'
        - 'Max': 'DataPortals/06.Setting-Details/Max.md'
        - 'Min': 'DataPortals/06.Setting-Details/Min.md'
        - 'Name': 'DataPortals/06.Setting-Details/Name.md'
        - 'OptionController': 'DataPortals/06.Setting-Details/OptionController.md'
        - 'Pattern': 'DataPortals/06.Setting-Details/Pattern.md'
        - 'PatternFlags': 'DataPortals/06.Setting-Details/PatternFlags.md'
        - 'ReadOnlyCondition': 'DataPortals/06.Setting-Details/ReadOnlyCondition.md'
        - 'RefreshComponents': 'DataPortals/06.Setting-Details/RefreshComponents.md'
        - 'Required': 'DataPortals/06.Setting-Details/Required.md'
        - 'SaveBeforeRun': 'DataPortals/06.Setting-Details/SaveBeforeRun.md'
        - 'SearchBoxes': 'DataPortals/06.Setting-Details/SearchBoxes.md'
        - 'Separator': 'DataPortals/06.Setting-Details/Separator.md'
        - 'StartLabel': 'DataPortals/06.Setting-Details/StartLabel.md'
        - 'StrMax': 'DataPortals/06.Setting-Details/StrMax.md'
        - 'StrMin': 'DataPortals/06.Setting-Details/StrMin.md'
        - 'Style': 'DataPortals/06.Setting-Details/Style.md'
        - 'TabIndex': 'DataPortals/06.Setting-Details/TabIndex.md'
        - 'Target': 'DataPortals/06.Setting-Details/Target.md'
        - 'Type': 'DataPortals/06.Setting-Details/Type.md'
        - 'UniqueConstraint': 'DataPortals/06.Setting-Details/UniqueConstraint.md'
        - 'UniqueConstraintScopeToParent': 'DataPortals/06.Setting-Details/UniqueConstraintScopeToParent.md'
        - 'ValidationCondition': 'DataPortals/06.Setting-Details/ValidationCondition.md'
        - 'VisibilityCondition': 'DataPortals/06.Setting-Details/VisibilityCondition.md'
    - '5.7 Categories': 'DataPortals/05.Categories.md'
    - '5.8 Setting Sheets': 'DataPortals/06.SettingSheet.md'
    - '5.9 Search': 'DataPortals/03.Search-Features.md'
    - '5.10 Updating DataPortals': 'DataPortals/10.UpdateDataPortals.md' 
- 6. DataRepository:
    - '6.1 Overview': 'DataRepository/01.Overview.md'
    - '6.2 DataRepository Basics': 'DataRepository/Create-DataRepository.md'
    - '6.3 Repository Details': 'DataRepository/Repository-Details.md'
    - '6.4 DataQuery': 'DataRepository/DataQuery-Overview.md'
- 7. DataCatalog:
    - '7.1 Overview': 'DataCatalogs/Overview.md'
- 8. DashBoards:
    - '8.1 Overview': 'DashBoards/01.Overview.md'
- 9. WebApps:
    - '9.1 Overview': 'WebApps/01.Overview.md'
    - '9.2 WebApp Basics': 'WebApps/02.WebApp-Basics.md'
- 10. Keys:
    - '10.1 Overview': 'Keys/01.Overview.md'
    - '10.2 Using Keys': 'Keys/02.Using-Keys.md'
- 11. Users and Groups:
    - '11.1 Overview': 'Users-and-Groups/01.Overview.md'
    - '11.2 User Profile': 'Users-and-Groups/02.User-Profile.md'

- 12. FluentAPI:
    - '12.1 FluentAPI User Guide': 'FluentAPI/01.FluentAPI-User-Guide.md'
    - '12.2 FluentAPI Reference': 'FluentAPI/02.FluentAPI-Reference.md'
- 13. Code Promotion:
    - '13.1 Overview': 'Code-Promotion/01.Overview.md'
    - '13.2 Setup': 'Code-Promotion/02.Setup.md'
    - '13.3 Optional Settings': 'Code-Promotion/03.Optional-Settings.md'
    - '13.4 Possible-Issues': 'Code-Promotion/04.Possible-Issues.md'
- Tutorials:
    - 'DataFlow: Word Count Using Python and C#': 'Tutorial/DataFlow-Word-Count.md'
    - 'DataFlow: Image Processing DataFlows': 'Tutorial/DataFlow-Image-Processing.md'
    - 'DataFlow: Reading in Data from the Web': 'Tutorial/ReadingBlueBikes.md'
    - 'DataPortal: Creating a Database and Inserting Data': 'Tutorial/BlueBikesDataPortal.md'
    - 'QueryView: Creation from a DataPortal and Functionality Demo': 'Tutorial/QueryViewDataPortal.md'
    - 'DataFlow: Lunch Recommender Slack App': 'Tutorial/Lunch.md'

markdown_extensions:
  - admonition
  - lightgallery:
      show_description_in_lightgallery: true  
